GET http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11cWVldCIsImlkIjoiNjE2YzgzOTk4MWZlYzUyNTdkY2I1NmY4IiwiaWF0IjoxNjM0NTQ5Mzk0fQ.cmfwapaTLcZI9awhlzFtv7DUrppk3gfBP4Gy7sWp4lk